### PR TITLE
docs: added screenshots to readme

### PR DESCRIPTION
**Pull request by muthukumarimoorthi**
i added all the screenshot for the configuration...

### CODE REVIEW

**Comment by anburocky3** [comment]
This is not i'm expecting.  Go and add the github actions.

**Comment by muthukumarimoorthi** [comment]
@anburocky3  i have added github actions screenshot and please conform is this correct or not? and i have one more doubt, shall i include YML configuration or not?

**Comment by anburocky3** [comment]
> @anburocky3 i have added github actions screenshot and please conform is this correct or not? and i have one more doubt, shall i include YML configuration or not?

The screenshots are correct, but it should be screenshotted in zoom and close unwanted tabs, its exposing your detail.s

You don't need to have the yml file, since this package ships it by default.

**Comment by muthukumarimoorthi** [comment]
@anburocky3 updated all things

**Comment by anburocky3** [comment]
Thanks @muthukumarimoorthi

**Pull request merged**
